import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {MAX_STROKES,addStroke,ablationCases,createStudy,fitStroke,recordUserReview,renderSparseSvg,replayHash,validateSparseStudy} from '../src/sparse-line-study.mjs';
const curriculum=JSON.parse(fs.readFileSync(new URL('../training/wonder-sparse-v1/shovel-studies.json',import.meta.url)));
const studies=curriculum.studies;
test('curriculum is modern shovel only and within Empty Glass budget',()=>{assert.equal(curriculum.sourcePolicy,'MODERN_OBJECTS_ONLY_FLESHPUNK_FORBIDDEN');assert.deepEqual(studies.map(s=>[s.subjectId,s.source.class,s.strokes.length]),[['shovel','MODERN_OBJECT',16],['shovel','MODERN_OBJECT',20]]);for(const study of studies)assert.deepEqual(validateSparseStudy(study).failures,[])});
test('fitter is deterministic and tighter error budget cannot use fewer cubics',()=>{const points=Array.from({length:21},(_,i)=>({x:i*4,y:40+Math.sin(i/3)*18}));const loose=fitStroke(points,4),tight=fitStroke(points,.35);assert.deepEqual(fitStroke(points,.35),tight);assert.ok(tight.length>=loose.length);assert.match(JSON.stringify(tight),/"x"/)});
test('stroke cap rejects the twenty-first stroke',()=>{let study=createStudy({subjectId:'test',sourceId:'modern',sourceSha256:'a'.repeat(64),view:'ASSEMBLED',width:100,height:100,sourceCrop:{x:0,y:0,width:100,height:100}});for(let i=0;i<MAX_STROKES;i++)study=addStroke(study,{id:`s${i}`,role:'SILHOUETTE',d:'M0 0 L1 1'});assert.throws(()=>addStroke(study,{id:'overflow',role:'CORRECTION',d:'M0 0 L2 2'}),/STROKE_BUDGET_EXCEEDED/)});
test('fleshpunk is rejected at source boundary',()=>{const poisoned=structuredClone(studies[0]);poisoned.source.id='fleshpunk-shovel';assert.match(validateSparseStudy(poisoned).failures.join(','),/FLESHPUNK_SOURCE_FORBIDDEN/)});
test('review cannot be recorded while reference is visible',()=>assert.throws(()=>recordUserReview(studies[0],{verdict:'RECOGNIZABLE',referenceHidden:false}),/REFERENCE_MUST_BE_HIDDEN/));
test('every stroke owns a visible ablation case',()=>{for(const study of studies){const cases=ablationCases(study);assert.equal(cases.length,study.strokes.length);for(const item of cases)assert.notEqual(renderSparseSvg(item.study,{omitStrokeId:item.omitStrokeId}),renderSparseSvg(study))}});
test('SVG export is line-only and contains no source payload',()=>{for(const study of studies){const svg=renderSparseSvg(study);assert.doesNotMatch(svg,/<image|data:|<script|<filter/i);assert.doesNotMatch(svg,/flesh/i);assert.match(svg,/<path/);assert.equal((svg.match(/<path/g)||[]).length,study.strokes.length)}});
test('same accepted record has stable replay hash',()=>assert.equal(replayHash(studies[0]),replayHash(JSON.parse(JSON.stringify(studies[0])))));
test('negative spaces must reference actual strokes',()=>{const broken=structuredClone(studies[0]);broken.negativeSpaces[0].strokeIds.push('missing');assert.match(validateSparseStudy(broken).failures.join(','),/BAD_NEGATIVE_SPACE/)});

test('review artifacts retain exact provenance and remain unaccepted',()=>{const provenance=JSON.parse(fs.readFileSync(new URL('../training/wonder-sparse-v1/PROVENANCE.json',import.meta.url)));assert.equal(provenance.transcription.artisticState,'AWAITING_USER_PIXEL_VERDICT');for(const artifact of provenance.artifacts){const bytes=fs.readFileSync(new URL(`../${artifact.path}`,import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),artifact.sha256);assert.equal(artifact.accepted,false)}});
test('browser adapter exposes the complete sparse review loop',()=>{const html=fs.readFileSync(new URL('../wonder/index.html',import.meta.url),'utf8'),script=fs.readFileSync(new URL('../wonder/studio.mjs',import.meta.url),'utf8');for(const marker of ['empty-glass-shovel-v1','Hide reference','Destructive test','Export SVG'])assert.match(html,new RegExp(marker));for(const behavior of ['pointerdown','localStorage','setAblationVerdict','recordUserReview'])assert.match(script,new RegExp(behavior))});
