import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {generateVectorImage,buildContactSheet,classifyPrompt} from '../src/vector-imagegen.mjs';
const genome=JSON.parse(fs.readFileSync(new URL('../training/style-genome.v1.json',import.meta.url))),prompts=JSON.parse(fs.readFileSync(new URL('../training/contact-sheet-prompts.v1.json',import.meta.url))).prompts;
test('any nonempty unfamiliar noun deterministically becomes one SVG subject',()=>{const a=generateVectorImage('quendorplex',genome),b=generateVectorImage('quendorplex',genome);assert.equal(a.state,'GENERATED');assert.equal(a.svg,b.svg);assert.equal(a.intent.family,'invented_subject');assert.match(a.svg,/^<svg/);});
test('empty input is the only ordinary invalid target',()=>assert.equal(classifyPrompt(' ').state,'TARGET_INVALID'));
test('detailed language controls counts view and exploded relations',()=>{const r=generateVectorImage(prompts[7],genome);assert.equal(r.intent.detail,'DETAILED');assert.equal(r.intent.counts.leg,6);assert.equal(r.intent.counts.turret,3);assert.match(r.intent.view,/three-quarter/);assert.equal(r.intent.exploded,true);assert.equal(r.graph.componentCounts.leg,6);assert.equal(r.graph.componentCounts.turret,3);assert.ok(r.clauseCoverage.every(x=>x.status==='COVERED'));});
test('bare and detailed prompts both work and detailed changes the program',()=>{const a=generateVectorImage('observatory',genome),b=generateVectorImage(prompts[7],genome);assert.equal(a.state,'GENERATED');assert.notEqual(a.programHash,b.programHash);assert.ok(b.graph.ops.length>a.graph.ops.length);});
test('trained style genome has causal effect',()=>{const a=generateVectorImage('cathedral crab',genome),b=generateVectorImage('cathedral crab',genome,{styleEnabled:false});assert.notEqual(a.svgHash,b.svgHash);assert.notEqual(a.graph.ops.length,b.graph.ops.length);});
test('ten prompt gate is unique pure line SVG and model free',()=>{const r=buildContactSheet(prompts,genome);assert.equal(r.images.length,10);assert.equal(new Set(r.images.map(x=>x.svgHash)).size,10);for(const x of r.images){assert.equal(x.aiCalls,0);assert.equal(x.critique.lineOnly,true);assert.doesNotMatch(x.svg,/<image|filter|linearGradient|radialGradient|fill="(?!none|#fffef9)/);}assert.equal(r.aiCalls,0);});
test('generator contains no random network model or ten-prompt presets',()=>{const src=fs.readFileSync(new URL('../src/vector-imagegen.mjs',import.meta.url),'utf8');assert.doesNotMatch(src,/Math\.random|fetch\(|from ['\"]https?:|safetensors|openai|comfy/i);for(const p of prompts)assert.equal(src.includes(p),false);});
