import {MAX_STROKES,REVIEW_SCALES,acceptanceFailures,addStroke,markSourceVerified,promoteUserAccepted,recordScaleReview,removeStroke,setAblationVerdict,renderSparseSvg,validateSparseStudy} from '../src/sparse-line-study.mjs';

const NS='http://www.w3.org/2000/svg',$=selector=>document.querySelector(selector),clone=value=>JSON.parse(JSON.stringify(value));
const curriculum=await fetch('../training/wonder-sparse-v1/shovel-studies.json',{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error(`study ${response.status}`);return response.json()});
const starters=new Map(curriculum.studies.map(study=>[study.view,study]));
let view='ASSEMBLED',study,referenceVisible=true,role='SILHOUETTE',activeScale=96,selectedId=null,ablationIndex=-1,drawing=false,rawPoints=[],history=[],future=[],sourceHref=null,sourceObjectUrl=null,verifiedSourceSha=null;
const storageKey=target=>`empty-glass-shovel-v2:${curriculum.sourceImage.sha256}:${target}`;
function restore(target=view){const saved=localStorage.getItem(storageKey(target));if(saved){try{const candidate=JSON.parse(saved);if(validateSparseStudy(candidate).failures.length===0)return candidate}catch{localStorage.removeItem(storageKey(target))}}return clone(starters.get(target))}
function persist(){localStorage.setItem(storageKey(view),JSON.stringify(study))}
function checkpoint(){history.push(clone(study));if(history.length>50)history.shift();future=[]}
function widthFor(stroke){return stroke.role==='SILHOUETTE'?2.8:stroke.role==='IDENTITY_ANCHOR'?1.9:1.3}
function displayStrokes(){return study.strokes.filter((_,index)=>index!==ablationIndex)}
function element(name,attributes={}){const node=document.createElementNS(NS,name);for(const [key,value] of Object.entries(attributes))node.setAttribute(key,value);return node}
function sourceIsVerified(){return study.source.verification?.state==='VERIFIED'&&study.source.verification.sha256===study.source.sha256&&verifiedSourceSha===study.source.sha256}
function drawMain(){const svg=$('#drawing'),crop=study.source.crop,reference=$('#reference');svg.setAttribute('viewBox',`0 0 ${study.canvas.width} ${study.canvas.height}`);if(sourceHref)reference.setAttribute('href',sourceHref);else reference.removeAttribute('href');reference.setAttribute('x',-crop.x);reference.setAttribute('y',-crop.y);reference.setAttribute('width',curriculum.sourceImage.width);reference.setAttribute('height',curriculum.sourceImage.height);reference.classList.toggle('hidden',!referenceVisible);const ink=$('#ink');ink.replaceChildren();for(const stroke of displayStrokes()){const path=element('path',{d:stroke.d,'data-role':stroke.role,'data-stroke':stroke.id});path.style.strokeWidth=widthFor(stroke);if(stroke.id===selectedId)path.classList.add('selected');ink.append(path)}}
function drawPreviews(){const host=$('#scale-previews');host.replaceChildren();for(const [size,label,className] of [[96,'thumbnail',''],[220,'normal','normal'],[360,'enlarged','large']]){const review=study.review.scales.find(item=>item.size===size),card=document.createElement('div');card.className=`preview-card ${className}${activeScale===size?' active':''}`;card.dataset.scale=size;card.style.setProperty('--review-size',`${size}px`);const span=document.createElement('span');span.textContent=`${label} · ${review.verdict??'UNREVIEWED'}`;const shell=document.createElement('div');shell.innerHTML=renderSparseSvg(study,{omitStrokeId:ablationIndex>=0?study.strokes[ablationIndex]?.id:null,title:`Shovel ${view} ${label}`});card.append(span,shell.firstElementChild);card.addEventListener('click',()=>{activeScale=size;render()});host.append(card)}}
function roleCopy(){return role==='SILHOUETTE'?['Pass 1 · silhouette','Outer mass first. No detail can rescue a generic silhouette.']:role==='IDENTITY_ANCHOR'?['Pass 2 · identity anchors','Add only the contours that make this shovel unmistakable.']:['Pass 3 · correction','Add ink only to repair a concrete hidden-reference misread.']}
function acceptedCount(){return ['ASSEMBLED','EXPLODED'].filter(target=>restore(target).state==='USER_ACCEPTED').length}
function uiBlockers(){const failures=acceptanceFailures(study,{referenceHidden:!referenceVisible});if(ablationIndex>=0)failures.push('ABLATION_ACTIVE');return [...new Set(failures)]}
function render(){if(ablationIndex>=study.strokes.length)ablationIndex=study.strokes.length-1;drawMain();drawPreviews();const [label,instruction]=roleCopy();$('#pass-label').textContent=label;$('#instruction').textContent=instruction;$('#budget').textContent=`${study.strokes.length} / ${MAX_STROKES} strokes`;$('#reference-toggle').textContent=referenceVisible?'Hide reference':'Show reference';document.querySelectorAll('[data-role]').forEach(button=>button.classList.toggle('active',button.dataset.role===role));$('#assembled').classList.toggle('active',view==='ASSEMBLED');$('#exploded').classList.toggle('active',view==='EXPLODED');$('#active-scale').textContent=`Reviewing ${activeScale} px`;const scaleReview=study.review.scales.find(item=>item.size===activeScale);document.querySelectorAll('[data-verdict]').forEach(button=>{button.disabled=referenceVisible||!sourceIsVerified()||ablationIndex>=0;button.classList.toggle('active',button.dataset.verdict===scaleReview.verdict)});const reviewLock=$('#review-lock');reviewLock.hidden=false;reviewLock.textContent=!sourceIsVerified()?'Verify the sealed modern source before review.':referenceVisible?'Hide the reference before recording a verdict.':ablationIndex>=0?'Return to the full drawing before recording scale recognition.':`Record the ${activeScale} px verdict.`;const current=ablationIndex>=0?study.strokes[ablationIndex]:null;$('#ablation-name').textContent=current?`WITHOUT ${current.id}`:'Full drawing';$('#ablation-note').textContent=current?`${current.ablationImportance} · ${current.note}`:'Each step removes exactly one stroke.';for(const id of ['essential','removable'])$("#"+id).disabled=!current||referenceVisible||!sourceIsVerified();const validation=validateSparseStudy(study),reviewed=study.strokes.filter(stroke=>stroke.ablationImportance!=='PENDING').length;$('#state').textContent=`${study.state} · ${reviewed}/${study.strokes.length} ablations · ${validation.replayHash}`;const blockers=uiBlockers(),accept=$('#accept-view');accept.disabled=blockers.length>0||study.state==='USER_ACCEPTED';$('#acceptance-blockers').textContent=study.state==='USER_ACCEPTED'?'This view is USER_ACCEPTED and hash-bound.':blockers.length?`Locked · ${blockers.slice(0,4).join(' · ')}${blockers.length>4?` · +${blockers.length-4} more`:''}`:'All gates are ready for your explicit acceptance.';$('#acceptance-blockers').classList.toggle('accepted',study.state==='USER_ACCEPTED');$('#curriculum-state').textContent=`${acceptedCount()} / 2 views accepted`;persist()}
function switchView(next){if(next===view)return;view=next;study=restore();if(verifiedSourceSha===study.source.sha256&&study.source.verification?.state!=='VERIFIED')study=markSourceVerified(study,verifiedSourceSha);referenceVisible=true;selectedId=null;ablationIndex=-1;activeScale=96;history=[];future=[];render()}
function svgPoint(event){const svg=$('#drawing'),point=svg.createSVGPoint();point.x=event.clientX;point.y=event.clientY;return point.matrixTransform(svg.getScreenCTM().inverse())}
function preview(){$('#preview').setAttribute('points',rawPoints.map(point=>`${point.x.toFixed(1)},${point.y.toFixed(1)}`).join(' '))}
function nextStrokeId(){let n=1;const ids=new Set(study.strokes.map(stroke=>stroke.id));while(ids.has(`user-${String(n).padStart(2,'0')}`))n++;return `user-${String(n).padStart(2,'0')}`}
async function sha256Hex(bytes){const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('')}
async function acceptSourceBytes(bytes,label,type='image/png'){const digest=await sha256Hex(bytes);if(digest!==curriculum.sourceImage.sha256)throw new Error(`REJECT:SOURCE_HASH_MISMATCH:${digest}`);if(sourceObjectUrl)URL.revokeObjectURL(sourceObjectUrl);sourceObjectUrl=URL.createObjectURL(new Blob([bytes],{type}));sourceHref=sourceObjectUrl;verifiedSourceSha=digest;if(study.source.verification?.state!=='VERIFIED')study=markSourceVerified(study,digest);$('#source-status').textContent=`Verified modern source · ${label}`;render()}
async function loadBundledSource(){try{const response=await fetch(curriculum.sourceImage.localHref,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);await acceptSourceBytes(await response.arrayBuffer(),'sealed local cache',response.headers.get('content-type')||'image/png')}catch(error){$('#source-status').textContent=`Source unavailable · load the modern sheet · ${error.message}`;render()}}

$('#drawing').addEventListener('pointerdown',event=>{const existing=event.target.dataset?.stroke;if(existing){selectedId=existing;render();return}if(!sourceIsVerified()){$('#state').textContent='REJECT:SOURCE_UNVERIFIED';return}if(study.strokes.length>=MAX_STROKES){$('#state').textContent='REJECT:STROKE_BUDGET_EXCEEDED';return}drawing=true;rawPoints=[svgPoint(event)];$('#drawing').setPointerCapture(event.pointerId);preview();event.preventDefault()});
$('#drawing').addEventListener('pointermove',event=>{if(!drawing)return;const next=svgPoint(event),last=rawPoints.at(-1);if(Math.hypot(next.x-last.x,next.y-last.y)>=1.2){rawPoints.push(next);preview()}event.preventDefault()});
function finishStroke(event){if(!drawing)return;drawing=false;$('#preview').setAttribute('points','');if(rawPoints.length<2)return;checkpoint();try{study=addStroke(study,{id:nextStrokeId(),rawPoints,role,note:$('#stroke-note').value.trim(),tolerance:1.5});selectedId=study.strokes.at(-1).id;$('#stroke-note').value=''}catch(error){study=history.pop();$('#state').textContent=error.message}render();event?.preventDefault()}
$('#drawing').addEventListener('pointerup',finishStroke);$('#drawing').addEventListener('pointercancel',finishStroke);$('#assembled').addEventListener('click',()=>switchView('ASSEMBLED'));$('#exploded').addEventListener('click',()=>switchView('EXPLODED'));document.querySelectorAll('[data-role]').forEach(button=>button.addEventListener('click',()=>{role=button.dataset.role;render()}));$('#reference-toggle').addEventListener('click',()=>{referenceVisible=!referenceVisible;render()});
$('#source-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{await acceptSourceBytes(await file.arrayBuffer(),file.name,file.type||'image/png')}catch(error){$('#source-status').textContent=error.message;render()}});
$('#ink').addEventListener('click',event=>{if(event.target.dataset.stroke){selectedId=event.target.dataset.stroke;render()}});$('#delete-selected').addEventListener('click',()=>{if(!selectedId)return;checkpoint();study=removeStroke(study,selectedId);selectedId=null;ablationIndex=-1;render()});
$('#prune').addEventListener('click',()=>{const removable=study.strokes.filter(stroke=>stroke.ablationImportance==='REMOVABLE');if(!removable.length)return;checkpoint();for(const stroke of removable)study=removeStroke(study,stroke.id);selectedId=null;ablationIndex=-1;render()});$('#undo').addEventListener('click',()=>{if(!history.length)return;future.push(clone(study));study=history.pop();render()});$('#redo').addEventListener('click',()=>{if(!future.length)return;history.push(clone(study));study=future.pop();render()});
$('#ablation-next').addEventListener('click',()=>{ablationIndex=study.strokes.length?(ablationIndex+1)%study.strokes.length:-1;selectedId=null;render()});$('#ablation-prev').addEventListener('click',()=>{ablationIndex=study.strokes.length?(ablationIndex<=0?study.strokes.length-1:ablationIndex-1):-1;selectedId=null;render()});$('#ablation-clear').addEventListener('click',()=>{ablationIndex=-1;render()});
function markAblation(verdict){if(ablationIndex<0||referenceVisible)return;checkpoint();study=setAblationVerdict(study,study.strokes[ablationIndex].id,verdict);ablationIndex=study.strokes.length?(ablationIndex+1)%study.strokes.length:-1;render()}$('#essential').addEventListener('click',()=>markAblation('ESSENTIAL'));$('#removable').addEventListener('click',()=>markAblation('REMOVABLE'));
document.querySelectorAll('[data-verdict]').forEach(button=>button.addEventListener('click',()=>{try{checkpoint();study=recordScaleReview(study,{size:activeScale,verdict:button.dataset.verdict,referenceHidden:!referenceVisible,note:$('#review-note').value.trim()});render()}catch(error){study=history.pop();$('#state').textContent=error.message}}));
async function saveAcceptance(){const response=await fetch('../api/wonder/save-study',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(study)});const result=await response.json();if(!response.ok)throw new Error(`SAVE_REJECTED:${result.reason}`);return result}
$('#accept-view').addEventListener('click',async()=>{try{checkpoint();study=promoteUserAccepted(study,{authority:'USER_GESTURE',referenceHidden:!referenceVisible});persist();render();const result=await saveAcceptance();$('#state').textContent=`${study.state} · durable receipt ${result.receipt}`;}catch(error){if(study.state!=='USER_ACCEPTED')study=history.pop();$('#state').textContent=error.message;render()}});
function download(name,type,text){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#export-svg').addEventListener('click',()=>download(`shovel-${view.toLowerCase()}.svg`,'image/svg+xml',renderSparseSvg(study)));$('#export-json').addEventListener('click',()=>download(`shovel-${view.toLowerCase()}.study.json`,'application/json',JSON.stringify({...study,replayHash:validateSparseStudy(study).replayHash},null,2)));$('#reset').addEventListener('click',()=>{if(!confirm(`Reset ${view.toLowerCase()} to the authored starter?`))return;checkpoint();study=clone(starters.get(view));if(verifiedSourceSha)study=markSourceVerified(study,verifiedSourceSha);selectedId=null;ablationIndex=-1;render()});

study=restore();render();await loadBundledSource();
