import {intervenePrimitive} from '../src/perceptual-geometry.mjs';
import {EVIDENCE_AXES,MAX_VISIBLE_STROKES,REVIEW_AXES,REVIEW_SCALES,VIEWS,acceptanceFailures,allStrokes,markSourceVerified,promoteUserAccepted,recordScaleReview,renderMechanismSvg,setAblationEvidence,setInteractionEvidence,setProofEvidence,validateMechanismStudy,visibleStrokes} from '../src/sparse-line-study.mjs';
const $=s=>document.querySelector(s),clone=v=>JSON.parse(JSON.stringify(v));
const curriculum=await fetch('../training/wonder-sparse-v1/shovel-studies.json',{cache:'no-store'}).then(r=>r.json());
const interventionSet=await fetch('../training/wonder-sparse-v1/primitive-interventions.json',{cache:'no-store'}).then(r=>r.json());
const starter=curriculum.study,storageKey='empty-glass-correspondence-v6:'+curriculum.sourceImage.sha256;
const cases=[...interventionSet.singles,...interventionSet.pairs];
let study=restore(),view='ASSEMBLED',referenceVisible=true,mapVisible=true,activeScale=96,interventionIndex=-1,ablationIndex=-1,sourceHref=null,sourceObjectUrl=null,verifiedSourceSha=null;
function restore(){try{const v=JSON.parse(localStorage.getItem(storageKey));if(!validateMechanismStudy(v).failures.length)return v}catch{}return clone(starter)}
function persist(){localStorage.setItem(storageKey,JSON.stringify(study))}
function sourceVerified(){return study.source.verification?.state==='VERIFIED'&&verifiedSourceSha===study.source.sha256}
function activeCase(){return interventionIndex>=0?cases[interventionIndex]:null}
function displayed(){const c=activeCase();if(!c)return study;let next=study;for(const input of c.inputs||[c.input])next=intervenePrimitive(next,input);return next}
function proofPending(){return [...study.proofEvidence,...study.interactionEvidence].some(item=>EVIDENCE_AXES.some(axis=>item[axis]==='PENDING'))}
function proofRecord(c){if(!c)return null;return c.kind==='PAIRWISE_PRIMITIVE'?study.interactionEvidence.find(x=>x.id===c.id):study.proofEvidence.find(x=>x.targetId===c.input.targetId)}
function parseSvg(svg){return new DOMParser().parseFromString(svg,'image/svg+xml').documentElement}
function omitted(){return ablationIndex>=0?visibleStrokes(study,view)[ablationIndex]?.id:null}
function drawMain(){const crop=study.source.views[view],reference=$('#reference'),drawing=$('#drawing');drawing.setAttribute('viewBox','0 0 '+study.canvas.width+' '+study.canvas.height);if(sourceHref)reference.setAttribute('href',sourceHref);else reference.removeAttribute('href');reference.setAttribute('x',-crop.x);reference.setAttribute('y',-crop.y);reference.setAttribute('width',curriculum.sourceImage.width);reference.setAttribute('height',curriculum.sourceImage.height);reference.classList.toggle('hidden',!referenceVisible);const svg=parseSvg(renderMechanismSvg(displayed(),{view,omitStrokeId:omitted(),showMap:mapVisible}));$('#ink').replaceChildren(...[...svg.children].slice(1).map(n=>document.importNode(n,true)))}
function drawPreviews(){const host=$('#scale-previews');host.replaceChildren();for(const size of REVIEW_SCALES){const card=document.createElement('button');card.className='preview-card'+(activeScale===size?' active':'');card.style.setProperty('--review-size',size+'px');card.innerHTML='<span>'+size+' px</span>';card.append(parseSvg(renderMechanismSvg(displayed(),{view,omitStrokeId:omitted()})));card.onclick=()=>{activeScale=size;render()};host.append(card)}}
function drawLedger(){const host=$('#part-ledger');host.replaceChildren();host.innerHTML='<strong>Exploded-derived proposals · '+study.parts.length+' regions · '+study.attachments.length+' candidate interfaces</strong>';const list=document.createElement('ol');for(const p of study.parts){const item=document.createElement('li');item.textContent=p.id+' ← '+p.sourceComponentId+' · uncertainty '+p.uncertainty+' · '+p.strokes.length+' paths';list.append(item)}for(const a of study.attachments){const item=document.createElement('li');item.textContent=a.id+' · '+a.partIds.join(' ↔ ')+' · gap '+a.interfaceGap+' · '+a.state;list.append(item)}host.append(list);const oral=$('#oral-exam');oral.innerHTML='<strong>Accessibility oral exam · no raster lookup</strong>';const q=document.createElement('ol');for(const [name,answer] of Object.entries(study.objectProgram.accessibilityAnswers)){const li=document.createElement('li');li.textContent=name+' · '+answer.state+' · '+answer.basis;q.append(li)}oral.append(q)}
function drawReviewAxes(){const host=$('#review-axes');host.replaceChildren();const options={CATEGORY:['RECOGNIZABLE','WRONG','GENERIC','OVERDRAWN'],INSTANCE:['MATCHED','WRONG_INSTANCE','GENERIC','OVERDRAWN'],MECHANISM:['PRESERVED','BROKEN','AMBIGUOUS','OVERDRAWN'],CROSS_VIEW:['SAME_OBJECT','DIFFERENT_OBJECT','AMBIGUOUS','OVERDRAWN']};for(const axis of REVIEW_AXES){const row=document.createElement('div');row.className='review-axis';row.append(Object.assign(document.createElement('span'),{textContent:axis}));for(const verdict of options[axis]){const b=document.createElement('button');b.textContent=verdict.replaceAll('_',' ');b.dataset.reviewAxis=axis;b.dataset.verdict=verdict;const item=study.review[view][axis].find(x=>x.size===activeScale);b.classList.toggle('active',item.verdict===verdict);b.disabled=referenceVisible||!sourceVerified()||Boolean(activeCase())||ablationIndex>=0;b.onclick=()=>{study=recordScaleReview(study,{view,axis,size:activeScale,verdict,referenceHidden:true,note:$('#review-note').value.trim()});render()};row.append(b)}host.append(row)}}
function blockers(){const f=acceptanceFailures(study);if(referenceVisible)f.push('CURRENT_REFERENCE_VISIBLE');if(activeCase())f.push('INTERVENTION_ACTIVE');if(ablationIndex>=0)f.push('ABLATION_ACTIVE');return[...new Set(f)]}
function render(){const strokes=visibleStrokes(study,view);if(ablationIndex>=strokes.length)ablationIndex=strokes.length-1;drawMain();drawPreviews();drawLedger();drawReviewAxes();$('#assembled').classList.toggle('active',view==='ASSEMBLED');$('#exploded').classList.toggle('active',view==='EXPLODED');$('#reference-toggle').textContent=referenceVisible?'Hide reference':'Show reference';$('#map-toggle').textContent=mapVisible?'Hide evidence map':'Show evidence map';$('#budget').textContent=strokes.length+' / '+MAX_VISIBLE_STROKES+' visible strokes';$('#active-scale').textContent='Reviewing '+view.toLowerCase()+' at '+activeScale+' px';const c=activeCase(),record=proofRecord(c),axis=$('#proof-axis').value;$('#intervention-name').textContent=c?(c.kind+' · '+c.id):'Base program';$('#intervention-note').textContent=c?JSON.stringify(c.inputs||[c.input]):'Delete, rotate, scale, and detach before stroke compression.';for(const b of document.querySelectorAll('[data-proof-value]')){b.disabled=!c||referenceVisible||!sourceVerified();b.classList.toggle('active',record?.[axis]===b.dataset.proofValue)}const stroke=ablationIndex>=0?strokes[ablationIndex]:null,strokeAxis=$('#stroke-axis').value;$('#ablation-name').textContent=stroke?'WITHOUT '+stroke.id:'Full '+view.toLowerCase()+' drawing';for(const b of document.querySelectorAll('[data-stroke-value]')){b.disabled=!stroke||referenceVisible||!sourceVerified()||proofPending()||Boolean(c);b.classList.toggle('active',stroke?.evidence[view][strokeAxis]===b.dataset.strokeValue)}$('#review-lock').textContent=!sourceVerified()?'Verify the sealed modern source first.':referenceVisible?'Hide the reference before judgment.':c?'Return to the base program for scale judgment.':ablationIndex>=0?'Return to full drawing for scale judgment.':'Judge category, instance, mechanism, and cross-view identity.';const validation=validateMechanismStudy(study),pending=[...study.proofEvidence,...study.interactionEvidence].flatMap(x=>EVIDENCE_AXES.filter(a=>x[a]==='PENDING')).length;$('#state').textContent=curriculum.state+' · '+pending+' primitive judgments pending · '+validation.replayHash;const failures=blockers();$('#accept-study').disabled=failures.length>0;$('#acceptance-blockers').textContent=failures.length?'Locked · '+failures.slice(0,6).join(' · ')+(failures.length>6?' · +'+(failures.length-6)+' more':''):'Ready for explicit human acceptance.';persist()}
for(const select of [$('#proof-axis'),$('#stroke-axis')])for(const axis of EVIDENCE_AXES)select.append(new Option(axis,axis));
$('#proof-axis').onchange=render;$('#stroke-axis').onchange=render;
$('#intervention-next').onclick=()=>{interventionIndex=(interventionIndex+1)%cases.length;ablationIndex=-1;render()};$('#intervention-prev').onclick=()=>{interventionIndex=interventionIndex<=0?cases.length-1:interventionIndex-1;ablationIndex=-1;render()};$('#intervention-clear').onclick=()=>{interventionIndex=-1;render()};
for(const b of document.querySelectorAll('[data-proof-value]'))b.onclick=()=>{const c=activeCase();if(!c||referenceVisible||!sourceVerified())return;const axis=$('#proof-axis').value;if(c.kind==='PAIRWISE_PRIMITIVE')study=setInteractionEvidence(study,{interactionId:c.id,axis,value:b.dataset.proofValue});else study=setProofEvidence(study,{targetId:c.input.targetId,axis,value:b.dataset.proofValue});render()};
$('#ablation-next').onclick=()=>{if(proofPending())return;interventionIndex=-1;const n=visibleStrokes(study,view).length;ablationIndex=n?(ablationIndex+1)%n:-1;render()};$('#ablation-prev').onclick=()=>{if(proofPending())return;interventionIndex=-1;const n=visibleStrokes(study,view).length;ablationIndex=n?(ablationIndex<=0?n-1:ablationIndex-1):-1;render()};$('#ablation-clear').onclick=()=>{ablationIndex=-1;render()};for(const b of document.querySelectorAll('[data-stroke-value]'))b.onclick=()=>{const stroke=visibleStrokes(study,view)[ablationIndex];if(!stroke||referenceVisible||!sourceVerified()||proofPending())return;study=setAblationEvidence(study,{strokeId:stroke.id,view,axis:$('#stroke-axis').value,value:b.dataset.strokeValue});render()};
function switchView(v){view=v;referenceVisible=true;activeScale=96;interventionIndex=-1;ablationIndex=-1;render()}$('#assembled').onclick=()=>switchView('ASSEMBLED');$('#exploded').onclick=()=>switchView('EXPLODED');$('#reference-toggle').onclick=()=>{referenceVisible=!referenceVisible;render()};$('#map-toggle').onclick=()=>{mapVisible=!mapVisible;render()};
async function sha(bytes){const d=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(d)].map(v=>v.toString(16).padStart(2,'0')).join('')}async function acceptSource(bytes,label,type){const digest=await sha(bytes);if(digest!==curriculum.sourceImage.sha256)throw new Error('REJECT:SOURCE_HASH_MISMATCH:'+digest);if(sourceObjectUrl)URL.revokeObjectURL(sourceObjectUrl);sourceObjectUrl=URL.createObjectURL(new Blob([bytes],{type:type||'image/png'}));sourceHref=sourceObjectUrl;verifiedSourceSha=digest;study=markSourceVerified(study,digest);$('#source-status').textContent='Verified modern source · '+label;render()}async function load(){try{const r=await fetch(curriculum.sourceImage.localHref,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);await acceptSource(await r.arrayBuffer(),'sealed local cache',r.headers.get('content-type'))}catch(e){$('#source-status').textContent=e.message;render()}}$('#source-file').onchange=async e=>{const f=e.target.files[0];if(f)try{await acceptSource(await f.arrayBuffer(),f.name,f.type)}catch(err){$('#source-status').textContent=err.message}};
function download(name,type,text){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}$('#export-svg').onclick=()=>download('modern-object-'+view.toLowerCase()+'.svg','image/svg+xml',renderMechanismSvg(study,{view}));$('#export-json').onclick=()=>download('modern-object.study.json','application/json',JSON.stringify(study,null,2));$('#reset').onclick=()=>{if(!confirm('Reset all correspondence evidence?'))return;study=clone(starter);if(verifiedSourceSha)study=markSourceVerified(study,verifiedSourceSha);view='ASSEMBLED';referenceVisible=true;interventionIndex=-1;ablationIndex=-1;render()};$('#accept-study').onclick=async()=>{try{study=promoteUserAccepted(study,{authority:'USER_GESTURE'});const r=await fetch('../api/wonder/save-study',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(study)}),j=await r.json();if(!r.ok)throw new Error(j.reason);$('#state').textContent='USER_ACCEPTED · '+j.receipt}catch(e){$('#state').textContent=e.message}};
render();await load();
