import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {compileRelationCandidate,discoverNeutralGeometry,matchExplodedComponents,mutateRelation,parsePathData,symmetricChamfer} from '../src/perceptual-geometry.mjs';
import {allStrokes,replayHash,validateMechanismStudy} from '../src/sparse-line-study.mjs';
const require=createRequire(import.meta.url),vtracer=require('@visioncortex/vtracer');
const root=path.resolve(new URL('..',import.meta.url).pathname),training=path.join(root,'training/wonder-sparse-v1');
const sourcePath=path.join(training,'source-cache/utility-normal.png'),studyPath=path.join(training,'shovel-studies.json');
const sourceBytes=fs.readFileSync(sourcePath),sourceSha256=createHash('sha256').update(sourceBytes).digest('hex'),EXPECTED='e4202ceb87bae2ab00d98b25999ab1105eda878d38904d97d070b63aff1fa923';
if(sourceSha256!==EXPECTED)throw new Error('REJECT:SOURCE_HASH_MISMATCH');
const oldCurriculum=JSON.parse(fs.readFileSync(studyPath,'utf8')),rejectedPath=path.join(training,'rejected-mechanism-v4.json'),oldStudy=JSON.parse(fs.readFileSync(rejectedPath,'utf8')).study,temp=fs.mkdtempSync(path.join(os.tmpdir(),'wonder-relations-'));process.on('exit',()=>fs.rmSync(temp,{recursive:true,force:true}));
function crop(name,{x,y,width,height}){const target=path.join(temp,name+'.png'),result=spawnSync('ffmpeg',['-loglevel','error','-i',sourcePath,'-vf',`crop=${width}:${height}:${x}:${y}`,'-frames:v','1','-y',target],{encoding:'utf8'});if(result.status!==0)throw new Error('REJECT:CROP_FAILED:'+result.stderr);return fs.readFileSync(target)}
function trace(buffer){return vtracer.convertBuffer(buffer,{clustering:'bw',mode:'spline',adaptive:true,adaptiveWindow:25,adaptiveT:7,filterSpeckle:8,cornerThreshold:60,lengthThreshold:4,simplify:1.6,pathPrecision:2,optimize:2})}
const views={ASSEMBLED:{x:0,y:0,width:397,height:397},EXPLODED:{x:0,y:397,width:397,height:396}},sibling={x:397,y:0,width:397,height:397};
const assembledSvg=trace(crop('assembled',views.ASSEMBLED)),explodedSvg=trace(crop('exploded',views.EXPLODED)),siblingSvg=trace(crop('sibling-modern-object',sibling));
const graph=discoverNeutralGeometry(assembledSvg,{view:'ASSEMBLED',partCount:4}),matches=matchExplodedComponents(graph,explodedSvg),candidate=compileRelationCandidate(graph,matches,{sourceSha256,sourceViews:views,subjectId:'shovel',sourceId:'utility-normal:column-0:paired'});
const siblingGraph=discoverNeutralGeometry(siblingSvg,{view:'ASSEMBLED',partCount:4});
const operatorFor=relation=>relation.type==='AXIS_ANGLE'?'ANGLE':relation.type==='LENGTH_RATIO'?'SCALE':relation.type==='JUNCTION_CONTINUITY'?'SIMPLIFY_JUNCTION':relation.type==='NEGATIVE_SPACE_ASPECT'?'REMOVE':null;
let variantsCounter=1;
const variants=graph.relations.flatMap(relation=>{const operator=operatorFor(relation);if(!operator)return[];const directions=operator==='REMOVE'?[1]:[-1,1];return directions.map(direction=>{const mutated=mutateRelation(candidate,{relationId:relation.id,operator,direction});return{id:'mutation-'+String(variantsCounter++).padStart(2,'0'),relationId:relation.id,relationType:relation.type,operator,direction,mutatedReplayHash:replayHash(mutated),verdict:{CATEGORY:'PENDING',STRUCTURE:'PENDING',authority:'HUMAN_ONLY'}}})});
function pointsFromStudy(study,view='ASSEMBLED'){const points=[];for(const part of study.parts){const m=part.poses[view];for(const stroke of part.strokes){if(stroke.visible[view]===false)continue;for(const contour of parsePathData(stroke.d))for(const p of contour)points.push({x:m[0]*p.x+m[2]*p.y+m[4],y:m[1]*p.x+m[3]*p.y+m[5]})}}return points}
function pathHashes(study){return new Set(allStrokes(study).map(stroke=>createHash('sha256').update(stroke.d).digest('hex')))}
const sourcePoints=graph.outer.points,oldPoints=pointsFromStudy(oldStudy),newPoints=pointsFromStudy(candidate),oldHashes=pathHashes(oldStudy),newHashes=pathHashes(candidate),sharedHashes=[...newHashes].filter(hash=>oldHashes.has(hash));
const antiNoop={oldCandidateReplayHash:replayHash(oldStudy),newCandidateReplayHash:replayHash(candidate),sharedPathHashCount:sharedHashes.length,assembledContourDelta:symmetricChamfer(oldPoints,newPoints),oldSourceError:symmetricChamfer(sourcePoints,oldPoints),newSourceError:symmetricChamfer(sourcePoints,newPoints),newToOldErrorRatio:Number((symmetricChamfer(sourcePoints,newPoints)/Math.max(.001,symmetricChamfer(sourcePoints,oldPoints))).toFixed(4)),oldVisibleStrokes:oldPoints.length?allStrokes(oldStudy).filter(s=>s.visible.ASSEMBLED!==false).length:0,newVisibleStrokes:allStrokes(candidate).filter(s=>s.visible.ASSEMBLED!==false).length};
if(sharedHashes.length)throw new Error('REJECT:STALE_PATH_REUSE');if(antiNoop.assembledContourDelta<Math.hypot(397,397)*.01||antiNoop.newVisibleStrokes>antiNoop.oldVisibleStrokes*.6)throw new Error('REJECT:VISUAL_NOOP');if(antiNoop.newSourceError>=antiNoop.oldSourceError*.7)throw new Error('REJECT:SOURCE_RELATION_ERROR_NOT_REDUCED');
const validation=validateMechanismStudy(candidate);if(validation.failures.length)throw new Error('REJECT:GENERATED_STUDY_INVALID:'+validation.failures.join('|'));
const proposals={assembledSha256:createHash('sha256').update(assembledSvg).digest('hex'),explodedSha256:createHash('sha256').update(explodedSvg).digest('hex'),tool:'@visioncortex/vtracer@1.0.0-alpha.4',status:'TEACHER_PROPOSAL_NOT_RUNTIME'};
const graphArtifact={schema:'vector-noodle.perceptual-geometry-evidence.v1',sourceSha256,method:'NEUTRAL_SOURCE_DERIVED',forbiddenSemantics:true,graph,siblingGenericityControl:{crop:sibling,graph:siblingGraph},proposals,antiNoop};
const mutationArtifact={schema:'vector-noodle.relation-mutation-set.v1',sourceSha256,order:'RELATION_BEFORE_STROKE',humanAuthority:true,variants};
const curriculum={schema:'vector-noodle.mechanism-line-curriculum.v1',state:'AWAITING_USER_PIXEL_VERDICT',sourcePolicy:'MODERN_OBJECTS_ONLY_FLESHPUNK_FORBIDDEN',sourceImage:oldCurriculum.sourceImage,commission:{question:'Which neutral geometric relationships must be right before sparse strokes can succeed?',pipeline:['SOURCE','CANDIDATE_LANDMARKS','LANDMARK_RELATIONS','DOMINANT_AXES_PROPORTIONS_ATTACHMENTS','CONTOUR_DECISIONS','STROKES','RELATION_ABLATION','STROKE_ABLATION'],strokeAxes:['CATEGORY','STRUCTURE','NOISE'],relationAxes:['CATEGORY','STRUCTURE'],strokeCeiling:20,strokeTarget:null,humanOwnsAcceptance:true},rejectedCandidate:{state:'USER_REJECTED_VISUAL_NOOP',replayHash:replayHash(oldStudy),reason:'BLOATED_CONTOUR_LINE_CHATTER_TANGLED_TRANSITION_WEAK_TERMINAL_PROPORTION'},antiNoop,study:candidate};
for(const [name,value] of [['landmark-graph.json',graphArtifact],['relation-mutations.json',mutationArtifact],['shovel-studies.json',curriculum]])fs.writeFileSync(path.join(training,name),JSON.stringify(value,null,2)+'\n');
console.log(JSON.stringify({state:'GENERATED_AWAITING_USER',parts:candidate.parts.length,strokes:allStrokes(candidate).length,relations:graph.relations.length,mutations:variants.length,antiNoop,validation}));
