import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {mutateRelation} from '../src/perceptual-geometry.mjs';
import {VIEWS,allStrokes,renderMechanismSvg,replayHash,validateMechanismStudy,visibleStrokes} from '../src/sparse-line-study.mjs';
const root=path.resolve(new URL('..',import.meta.url).pathname),out=path.join(root,'evidence/wonder-sparse'),training=path.join(root,'training/wonder-sparse-v1');fs.mkdirSync(out,{recursive:true});
const curriculum=JSON.parse(fs.readFileSync(path.join(training,'shovel-studies.json'))),study=curriculum.study,rejected=JSON.parse(fs.readFileSync(path.join(training,'rejected-mechanism-v4.json'))).study,mutations=JSON.parse(fs.readFileSync(path.join(training,'relation-mutations.json')));
const inner=svg=>svg.replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,''),escape=value=>String(value).replace(/[&<>]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[char]));
function legacySvg(data,view,{omit=null}={}){const groups=data.parts.map(part=>'<g transform="matrix('+part.poses[view].join(' ')+')">'+part.strokes.filter(stroke=>stroke.visible[view]!==false&&stroke.id!==omit).map(stroke=>'<path d="'+stroke.d+'" fill="none" stroke="#171512" stroke-width="'+(stroke.role==='SILHOUETTE'?2.8:1.7)+'" stroke-linecap="round" stroke-linejoin="round"/>').join('')+'</g>').join('');return'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 397 397"><rect width="100%" height="100%" fill="#fffdf7"/>'+groups+'</svg>'}
const css='<style>.bg{fill:#171512}.paper{fill:#fffdf7}.title{font:900 28px system-ui;fill:#fffdf7}.label{font:800 11px system-ui;fill:#e5b55a;letter-spacing:1px}.note{font:13px monospace;fill:#aaa298}.axis{stroke:#315f8e;stroke-width:2;stroke-dasharray:8 5}.relation{stroke:#c94b3b;stroke-width:2;fill:none}.landmark{fill:#e5b55a;stroke:#171512;stroke-width:1}.part{fill:none;stroke:#c94b3b;stroke-width:1;stroke-dasharray:4 3}</style>';
function pair(view){return'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 880 510">'+css+'<rect width="100%" height="100%" class="bg"/><text x="28" y="42" class="title">'+view+' · REJECTED BEFORE / RELATION-FIRST AFTER</text><text x="28" y="70" class="note">same sealed source · zero reused path hashes · human verdict remains pending</text><g transform="translate(28 96)"><text class="label" y="-10">BEFORE · USER REJECTED</text><svg width="397" height="397" viewBox="0 0 397 397">'+inner(legacySvg(rejected,view))+'</svg></g><g transform="translate(455 96)"><text class="label" y="-10">AFTER · SOURCE-DERIVED RELATIONS</text><svg width="397" height="397" viewBox="0 0 397 397">'+inner(renderMechanismSvg(study,{view}))+'</svg></g></svg>'}
for(const view of VIEWS)fs.writeFileSync(path.join(out,'before-after-'+view.toLowerCase()+'-v5.svg'),pair(view)+'\n');
const graph=study.landmarkGraph,axisStart={x:graph.outer.frame.centroid.x+graph.outer.frame.axis.x*graph.outer.frame.min,y:graph.outer.frame.centroid.y+graph.outer.frame.axis.y*graph.outer.frame.min},axisEnd={x:graph.outer.frame.centroid.x+graph.outer.frame.axis.x*graph.outer.frame.max,y:graph.outer.frame.centroid.y+graph.outer.frame.axis.y*graph.outer.frame.max};
const partBoxes=graph.parts.map(part=>'<rect class="part" x="'+part.bbox.x+'" y="'+part.bbox.y+'" width="'+part.bbox.width+'" height="'+part.bbox.height+'"/><text x="'+(part.bbox.x+3)+'" y="'+(part.bbox.y+13)+'" class="note">'+part.id+'</text>').join(''),landmarks=graph.landmarks.map(item=>'<circle class="landmark" cx="'+item.point.x+'" cy="'+item.point.y+'" r="4"/><text x="'+(item.point.x+6)+'" y="'+(item.point.y-6)+'" class="note">'+item.id+' '+item.type+'</text>').join('');
const ledger=graph.relations.map((relation,index)=>'<text x="455" y="'+(112+index*27)+'" class="note">'+escape(relation.id+' · '+relation.type+' · '+relation.members.join(' / '))+'</text>').join('');
const graphSvg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 980 540">'+css+'<rect width="100%" height="100%" class="bg"/><text x="28" y="42" class="title">NEUTRAL LANDMARK / RELATION GRAPH</text><text x="28" y="70" class="note">extrema · width minima · enclosed regions · no object-part ontology</text><g transform="translate(28 100)"><svg width="397" height="397" viewBox="0 0 397 397">'+inner(renderMechanismSvg(study,{view:'ASSEMBLED'}))+'<line class="axis" x1="'+axisStart.x+'" y1="'+axisStart.y+'" x2="'+axisEnd.x+'" y2="'+axisEnd.y+'"/>'+partBoxes+landmarks+'</svg></g><text x="455" y="90" class="label">DISCOVERED RELATIONS</text>'+ledger+'</svg>';fs.writeFileSync(path.join(out,'neutral-landmark-relation-graph-v5.svg'),graphSvg+'\n');
const relationSpec=mutations.variants.find(item=>item.relationType==='LENGTH_RATIO'&&item.direction===1),relationStudy=mutateRelation(study,relationSpec),stroke=visibleStrokes(study,'ASSEMBLED').at(-1),relationSvg=renderMechanismSvg(relationStudy,{view:'ASSEMBLED'}),strokeSvg=renderMechanismSvg(study,{view:'ASSEMBLED',omitStrokeId:stroke.id});
const contrast='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1310 520">'+css+'<rect width="100%" height="100%" class="bg"/><text x="28" y="42" class="title">RELATION DISTORTION BEFORE STROKE ABLATION</text><text x="28" y="70" class="note">candidate perceptual contrast · machine cannot grant the recognition verdict</text>'+[['BASE',renderMechanismSvg(study,{view:'ASSEMBLED'})],['PERTURB '+relationSpec.relationId+' '+relationSpec.operator,relationSvg],['REMOVE '+stroke.id,strokeSvg]].map(([label,svg],index)=>'<g transform="translate('+(28+index*427)+' 102)"><text class="label" y="-12">'+label+'</text><svg width="397" height="397" viewBox="0 0 397 397">'+inner(svg)+'</svg></g>').join('')+'</svg>';fs.writeFileSync(path.join(out,'relation-vs-stroke-ablation-v5.svg'),contrast+'\n');
const scaleCards=[96,220,360].map((size,index)=>'<g transform="translate('+(28+(index===0?0:index===1?125:374))+' 105)"><text class="label" y="-10">'+size+' PX</text><svg width="'+size+'" height="'+size+'" viewBox="0 0 397 397">'+inner(renderMechanismSvg(study,{view:'ASSEMBLED'}))+'</svg></g>').join(''),scale='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 520">'+css+'<rect width="100%" height="100%" class="bg"/><text x="28" y="42" class="title">AFTER · THREE SCALE PIXEL GATE</text><text x="28" y="70" class="note">five visible strokes · 20 is a ceiling, not a target</text>'+scaleCards+'</svg>';fs.writeFileSync(path.join(out,'after-three-scale-v5.svg'),scale+'\n');
const artifacts=['before-after-assembled-v5.svg','before-after-exploded-v5.svg','neutral-landmark-relation-graph-v5.svg','relation-vs-stroke-ablation-v5.svg','after-three-scale-v5.svg'].map(name=>({path:'evidence/wonder-sparse/'+name,sha256:createHash('sha256').update(fs.readFileSync(path.join(out,name))).digest('hex'),accepted:false}));
const gate={schema:'vector-noodle.visual-gate.v5',buildMarker:'empty-glass-relations-v5',state:'AWAITING_USER_PIXEL_VERDICT',acceptance:false,sourceSha256:study.source.sha256,oldReplayHash:replayHash(rejected),newReplayHash:replayHash(study),antiNoop:curriculum.antiNoop,relationContrast:{relationId:relationSpec.relationId,operator:relationSpec.operator,strokeControl:stroke.id,CATEGORY:'PENDING_HUMAN',STRUCTURE:'PENDING_HUMAN'},guardrail:validateMechanismStudy(study),artifacts};fs.writeFileSync(path.join(out,'visual-gate-v5.json'),JSON.stringify(gate,null,2)+'\n');console.log(JSON.stringify({state:'RENDERED_AWAITING_USER',artifacts:artifacts.length,gate:path.join(out,'visual-gate-v5.json')}));
