import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {intervenePrimitive} from '../src/perceptual-geometry.mjs';
import {VIEWS,allStrokes,renderMechanismSvg,replayHash,validateMechanismStudy} from '../src/sparse-line-study.mjs';
const root=path.resolve(new URL('..',import.meta.url).pathname),out=path.join(root,'evidence/wonder-sparse'),training=path.join(root,'training/wonder-sparse-v1');
fs.mkdirSync(out,{recursive:true});
const curriculum=JSON.parse(fs.readFileSync(path.join(training,'shovel-studies.json'))),study=curriculum.study;
const rejected=JSON.parse(fs.readFileSync(path.join(training,'rejected-relation-v5.json'))).study;
const correspondence=JSON.parse(fs.readFileSync(path.join(training,'paired-correspondence.json'))),interventions=JSON.parse(fs.readFileSync(path.join(training,'primitive-interventions.json')));
const inner=svg=>svg.replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'');
const esc=value=>String(value).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const css='<style>.bg{fill:#171512}.paper{fill:#fffdf7}.title{font:900 26px system-ui;fill:#fffdf7}.label{font:800 11px system-ui;fill:#e5b55a;letter-spacing:1px}.note{font:12px monospace;fill:#aaa298}.good{fill:#86b37f}.warn{fill:#e5b55a}.bad{fill:#d56857}.edge{stroke:#e5b55a;stroke-width:2;stroke-dasharray:6 4}.map{fill:none;stroke-width:2}.unknown{fill:#332e29;stroke:#e5b55a;stroke-width:1}</style>';
function legacySvg(data,view){const groups=data.parts.map(part=>'<g transform="matrix('+part.poses[view].join(' ')+')">'+part.strokes.filter(s=>s.visible[view]!==false).map(s=>'<path d="'+s.d+'" fill="none" stroke="#171512" stroke-width="'+(s.role==='SILHOUETTE'?2.8:1.7)+'" stroke-linecap="round" stroke-linejoin="round"/>').join('')+'</g>').join('');return'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 397 397"><rect width="100%" height="100%" fill="#fffdf7"/>'+groups+'</svg>'}
function card(label,svg,x){return'<g transform="translate('+x+' 100)"><text class="label" y="-12">'+esc(label)+'</text><svg width="397" height="397" viewBox="0 0 397 397">'+inner(svg)+'</svg></g>'}
function beforeAfter(view){return'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 880 525">'+css+'<rect width="100%" height="100%" class="bg"/><text x="28" y="40" class="title">'+view+' · REJECTED SLICER / CORRESPONDENCE-FIRST</text><text x="28" y="67" class="note">candidate pixels only · no metric or machine may accept construction</text>'+card('BEFORE · VISUAL REJECT',legacySvg(rejected,view),28)+card('AFTER · HUMAN COHERENCE PENDING',renderMechanismSvg(study,{view}),455)+'</svg>'}
for(const view of VIEWS)fs.writeFileSync(path.join(out,'before-after-'+view.toLowerCase()+'-v6.svg'),beforeAfter(view)+'\n');
const colors=['#d56857','#69a7c7','#8bb174','#c79ad8'];
function mapped(view){let paths='',boxes='',centers=[];study.parts.forEach((part,index)=>{const color=colors[index%colors.length],m=part.poses[view],box=part.sourceEvidence[view],cx=box.x+box.width/2,cy=box.y+box.height/2;centers.push({id:part.id,x:cx,y:cy,color});paths+='<g transform="matrix('+m.join(' ')+')">'+part.strokes.map(s=>'<path d="'+s.d+'" fill="none" stroke="'+color+'" stroke-width="3" stroke-linejoin="round"/>').join('')+'</g>';boxes+='<rect x="'+box.x+'" y="'+box.y+'" width="'+box.width+'" height="'+box.height+'" class="map" stroke="'+color+'" stroke-dasharray="5 3"/><text x="'+(box.x+3)+'" y="'+(box.y+14)+'" class="note" fill="'+color+'">'+part.id+'</text>'});let edges='';for(const edge of study.attachments){const a=centers.find(c=>c.id===edge.partIds[0]),b=centers.find(c=>c.id===edge.partIds[1]);edges+='<line x1="'+a.x+'" y1="'+a.y+'" x2="'+b.x+'" y2="'+b.y+'" class="edge"/>'}return'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 397 397"><rect width="100%" height="100%" fill="#fffdf7"/>'+edges+paths+boxes+'</svg>'}
const rows=study.parts.map((part,index)=>{const component=correspondence.spec.components[index];return'<text x="885" y="'+(122+index*52)+'" class="note">'+esc(part.id+' ← '+part.sourceComponentId+'  score '+component.assembledHypothesis.score+'  uncertainty '+part.uncertainty)+'</text><text x="885" y="'+(140+index*52)+'" class="note">exploded region '+component.explodedEvidence.bbox.join(', ')+'</text>'}).join('');
const edges=study.attachments.map((edge,index)=>'<text x="885" y="'+(350+index*25)+'" class="note">'+esc(edge.id+' '+edge.partIds.join(' ↔ ')+' gap '+edge.interfaceGap+' · CANDIDATE')+'</text>').join('');
const mapSheet='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1350 530">'+css+'<rect width="100%" height="100%" class="bg"/><text x="28" y="40" class="title">PAIRED COMPONENT CORRESPONDENCE · NOT A PART COUNT REQUEST</text><text x="28" y="67" class="note">four regions emerged from a 2.445 area gap · assembled registration remains human-pending</text>'+card('ASSEMBLED HYPOTHESES',mapped('ASSEMBLED'),28)+card('EXPLODED ISOLATED EVIDENCE',mapped('EXPLODED'),455)+'<text x="885" y="92" class="label">PROOF LEDGER</text>'+rows+'<text x="885" y="322" class="label">ATTACHMENT HYPOTHESES</text>'+edges+'</svg>';
fs.writeFileSync(path.join(out,'paired-component-correspondence-v6.svg'),mapSheet+'\n');
const detach=interventions.singles.find(x=>x.kind==='SINGLE_ATTACHMENT'),remove=interventions.singles.find(x=>x.input.operator==='REMOVE');
const detached=intervenePrimitive(study,detach.input),removed=intervenePrimitive(study,remove.input);
const interventionSheet='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1310 525">'+css+'<rect width="100%" height="100%" class="bg"/><text x="28" y="40" class="title">PROOF-CARRYING INTERVENTION GATE</text><text x="28" y="67" class="note">delete or detach before compression · all seven judgment axes remain human-pending</text>'+card('BASE',renderMechanismSvg(study,{view:'ASSEMBLED'}),28)+card(detach.input.targetId+' DETACH',renderMechanismSvg(detached,{view:'ASSEMBLED'}),455)+card(remove.input.targetId+' REMOVE',renderMechanismSvg(removed,{view:'ASSEMBLED'}),882)+'</svg>';
fs.writeFileSync(path.join(out,'primitive-interventions-v6.svg'),interventionSheet+'\n');
let pairStudy=study;for(const input of interventions.pairs[0].inputs)pairStudy=intervenePrimitive(pairStudy,input);
const pairSheet='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 880 525">'+css+'<rect width="100%" height="100%" class="bg"/><text x="28" y="40" class="title">PAIRWISE ABLATION · INTERACTION ORE</text><text x="28" y="67" class="note">two primitives may carry evidence jointly that neither carries alone</text>'+card('BASE',renderMechanismSvg(study,{view:'ASSEMBLED'}),28)+card(interventions.pairs[0].inputs.map(x=>x.targetId).join(' + ')+' REMOVED',renderMechanismSvg(pairStudy,{view:'ASSEMBLED'}),455)+'</svg>';
fs.writeFileSync(path.join(out,'pairwise-intervention-v6.svg'),pairSheet+'\n');
const scales=[96,220,360].map((size,index)=>'<g transform="translate('+(28+[0,125,374][index])+' 110)"><text class="label" y="-10">'+size+' PX</text><svg width="'+size+'" height="'+size+'" viewBox="0 0 397 397">'+inner(renderMechanismSvg(study,{view:'ASSEMBLED'}))+'</svg></g>').join('');
const scaleSheet='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 525">'+css+'<rect width="100%" height="100%" class="bg"/><text x="28" y="40" class="title">THREE-SCALE CANDIDATE · SEVEN STROKES</text><text x="28" y="67" class="note">20 remains a ceiling · visual identity and mechanism remain unaccepted</text>'+scales+'</svg>';
fs.writeFileSync(path.join(out,'after-three-scale-v6.svg'),scaleSheet+'\n');
const questions=Object.entries(study.objectProgram.accessibilityAnswers).map(([key,value],index)=>'<g transform="translate(34 '+(105+index*61)+')"><rect width="900" height="43" rx="4" class="unknown"/><text x="14" y="18" class="label">'+esc(key)+'</text><text x="245" y="18" class="warn note">'+value.state+'</text><text x="330" y="18" class="note">'+esc(value.basis)+'</text></g>').join('');
const oral='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 980 500">'+css+'<rect width="100%" height="100%" class="bg"/><text x="28" y="40" class="title">ACCESSIBILITY ORAL EXAM · HONEST FAILURE</text><text x="28" y="67" class="note">answers must come from the object program, never by looking back at pixels</text>'+questions+'</svg>';
fs.writeFileSync(path.join(out,'accessibility-oral-exam-v6.svg'),oral+'\n');
const names=['before-after-assembled-v6.svg','before-after-exploded-v6.svg','paired-component-correspondence-v6.svg','primitive-interventions-v6.svg','pairwise-intervention-v6.svg','after-three-scale-v6.svg','accessibility-oral-exam-v6.svg'];
const artifacts=names.map(name=>({path:'evidence/wonder-sparse/'+name,sha256:createHash('sha256').update(fs.readFileSync(path.join(out,name))).digest('hex'),accepted:false}));
const gate={schema:'vector-noodle.visual-gate.v6',buildMarker:'empty-glass-correspondence-v6',state:'AWAITING_HUMAN_COMPONENT_COHERENCE',acceptance:false,sourceSha256:study.source.sha256,rejectedReplayHash:replayHash(rejected),candidateReplayHash:replayHash(study),diagnostics:{...curriculum.diagnostics,qualityAuthority:false},requirements:{sameCanonicalPathsBothViews:true,fixedPartCount:false,fractionalFallbackCuts:false,artificialCutFaces:false,accessibilityAnswersMayBeUnknown:true},guardrail:validateMechanismStudy(study),artifacts};
fs.writeFileSync(path.join(out,'visual-gate-v6.json'),JSON.stringify(gate,null,2)+'\n');
console.log(JSON.stringify({state:gate.state,artifacts:artifacts.length,gate:path.join(out,'visual-gate-v6.json')}));
