import fs from 'node:fs';
import path from 'node:path';
import {renderSparseSvg,validateSparseStudy} from '../src/sparse-line-study.mjs';
const root=path.resolve(new URL('..',import.meta.url).pathname);
const curriculum=JSON.parse(fs.readFileSync(path.join(root,'training/wonder-sparse-v1/shovel-studies.json'),'utf8'));
const out=path.join(root,'evidence/wonder-sparse');fs.mkdirSync(out,{recursive:true});
const inner=study=>renderSparseSvg(study).replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'');
for(const study of curriculum.studies)fs.writeFileSync(path.join(out,`shovel-${study.view.toLowerCase()}.svg`),renderSparseSvg(study)+"\n");
const cards=[];let x=40;
for(const study of curriculum.studies){for(const [size,label] of [[96,'THUMBNAIL'],[220,'NORMAL'],[360,'ENLARGED']]){cards.push(`<g transform="translate(${x} 132)"><text class="small" y="-18">${study.view} · ${label}</text><rect width="${size}" height="${size}" class="paper"/><svg width="${size}" height="${size}" viewBox="0 0 ${study.canvas.width} ${study.canvas.height}">${inner(study)}</svg></g>`);x+=size+34}}
const scale=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${x+10} 560"><style>.bg{fill:#171512}.paper{fill:#fffdf7}.title{font:900 34px system-ui;fill:#fffdf7}.small{font:800 12px system-ui;fill:#e5b55a;letter-spacing:1px}.note{font:15px system-ui;fill:#aaa298}</style><rect width="100%" height="100%" class="bg"/><text x="40" y="54" class="title">EMPTY GLASS · SHOVEL RECOGNITION CORE</text><text x="40" y="86" class="note">Reference hidden · modern object only · machine state: AWAITING USER PIXEL VERDICT</text>${cards.join('')}</svg>`;
fs.writeFileSync(path.join(out,'shovel-three-scale.svg'),scale+'\n');
const all=curriculum.studies.flatMap(study=>study.strokes.map(stroke=>({study,stroke}))),columns=4,cardW=280,cardH=305,rows=Math.ceil(all.length/columns),ablationCards=all.map(({study,stroke},index)=>{const col=index%columns,row=Math.floor(index/columns),ox=30+col*cardW,oy=110+row*cardH;return `<g transform="translate(${ox} ${oy})"><text class="label" y="-26">${study.view} · WITHOUT</text><text class="name" y="-8">${stroke.id}</text><rect width="250" height="250" class="paper"/><svg width="250" height="250" viewBox="0 0 ${study.canvas.width} ${study.canvas.height}">${renderSparseSvg(study,{omitStrokeId:stroke.id}).replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'')}</svg></g>`}).join('');
const ablation=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${30+columns*cardW} ${140+rows*cardH}"><style>.bg{fill:#171512}.paper{fill:#fffdf7}.title{font:900 30px system-ui;fill:#fffdf7}.label{font:800 10px system-ui;fill:#e5b55a;letter-spacing:1px}.name{font:12px monospace;fill:#fffdf7}</style><rect width="100%" height="100%" class="bg"/><text x="30" y="48" class="title">DESTRUCTIVE STROKE TEST · UNJUDGED</text><text x="30" y="78" class="name">Each card removes exactly one candidate stroke. Human judgment decides what earns ink.</text>${ablationCards}</svg>`;
fs.writeFileSync(path.join(out,'shovel-ablation.svg'),ablation+'\n');
const validation=curriculum.studies.map(study=>({view:study.view,strokeCount:study.strokes.length,...validateSparseStudy(study)}));
fs.writeFileSync(path.join(out,'visual-gate.json'),JSON.stringify({schema:'vector-noodle.visual-gate.v1',buildMarker:'empty-glass-shovel-v1',state:'AWAITING_USER_PIXEL_VERDICT',expected:'Recognizable modern shovel at thumbnail, normal, and enlarged scale with every retained stroke surviving human ablation.',actual:'Authored sparse candidate available; no human recognition or ablation verdict recorded.',acceptance:false,guardrails:validation,sourceComparison:'LOCAL_ONLY_SOURCE_NOT_COMMITTED',forbiddenTraining:'FLESHPUNK'},null,2)+'\n');
fs.writeFileSync(path.join(root,'evidence/wonder-v2/REJECTION.json'),JSON.stringify({schema:'vector-noodle.rejected-evidence.v1',state:'USER_REJECTED',artifacts:['gate-03-centerlines.svg','gate-04-correspondence.svg','gate-05-leave-one-out.svg'],reason:'Raster skeletons, spatial blob matching, and hand-authored ontology prediction do not prove visual learning.',replacement:'../wonder-sparse/shovel-three-scale.svg'},null,2)+'\n');
console.log(JSON.stringify({state:'RENDERED_AWAITING_USER',outputs:4,validation}));
